### ISSUE TITLE
Bump node to 18 as required by ckeditor5-dev-utils

### ISSUE THREAD

**Issue by wizhippo** [ibexa/docker#30]
ibexa 4.6.0 needs node >= 18 for the "@ckeditor/ckeditor5-dev-utils": "^39.0.0",

Perhaps ghcr.io/ibexa/docker/php:8.2-node18 should be default image now?

**Comment by mnocon** [comment]
Good idea, thanks! https://github.com/ibexa/recipes-dev/pull/109 should take care of this
